spring.application.name=fegaac1

# JDBC URL for MySQL (WAMP default: localhost, port 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/fegaac?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true

# MySQL user credentials (adjust if different)
spring.datasource.username=root
spring.datasource.password=

# MySQL JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate config for MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server config
server.port=8089




# SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gaialouis42@gmail.com
spring.mail.password=djxh ygks xtao bzbw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true